<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class countrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        $admins = array(
            array('code' => 'AF','capital' => 'afghanistan','name_en' => 'Afghanistan','name' => 'أفغانستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AX','capital' => 'aland-islands','name_en' => 'Aland Islands','name' => 'جزر آلاند','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AL','capital' => 'albania','name_en' => 'Albania','name' => 'ألبانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'DZ','capital' => 'algeria','name_en' => 'Algeria','name' => 'الجزائر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AS','capital' => 'american-samoa','name_en' => 'American Samoa','name' => 'ساموا الأمريكية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AD','capital' => 'andorra','name_en' => 'Andorra','name' => 'أندورا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AO','capital' => 'angola','name_en' => 'Angola','name' => 'أنغولا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AI','capital' => 'anguilla','name_en' => 'Anguilla','name' => 'أنغيلا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AG','capital' => 'antigua-and-barbuda','name_en' => 'Antigua and Barbuda','name' => 'أنتيغوا وبربودا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AR','capital' => 'argentina','name_en' => 'Argentina','name' => 'الأرجنتين','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AM','capital' => 'armenia','name_en' => 'Armenia','name' => 'أرمينيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AW','capital' => 'aruba','name_en' => 'Aruba','name' => 'أروبا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AU','capital' => 'australia','name_en' => 'Australia','name' => 'أستراليا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AT','capital' => 'austria','name_en' => 'Austria','name' => 'النمسا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AZ','capital' => 'azerbaijan','name_en' => 'Azerbaijan','name' => 'أذربيجان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BS','capital' => 'bahamas','name_en' => 'Bahamas','name' => 'جزر البهاما','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BH','capital' => 'bahrain','name_en' => 'Bahrain','name' => 'البحرين','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BD','capital' => 'bangladesh','name_en' => 'Bangladesh','name' => 'بنغلاديش','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BB','capital' => 'barbados','name_en' => 'Barbados','name' => 'بربادوس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BY','capital' => 'belarus','name_en' => 'Belarus','name' => 'بيلاروسيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BE','capital' => 'belgium','name_en' => 'Belgium','name' => 'بلجيكا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BZ','capital' => 'belize','name_en' => 'Belize','name' => 'بليز','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BJ','capital' => 'benin','name_en' => 'Benin','name' => 'بنين','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BM','capital' => 'bermuda','name_en' => 'Bermuda','name' => 'برمودا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BT','capital' => 'bhutan','name_en' => 'Bhutan','name' => 'بوتان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BO','capital' => 'bolivia','name_en' => 'Bolivia, Plurinational State of','name' => 'بوليفيا ، دولة متعددة القوميات','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BQ','capital' => 'bonaire','name_en' => 'Bonaire, Sint Eustatius and Saba','name' => 'بونير وسانت يوستاتيوس وسابا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BA','capital' => 'bosnia-and-herzegovina','name_en' => 'Bosnia and Herzegovina','name' => 'البوسنة والهرسك','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BW','capital' => 'botswana','name_en' => 'Botswana','name' => 'بوتسوانا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BR','capital' => 'brazil','name_en' => 'Brazil','name' => 'البرازيل','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IO','capital' => 'british-indian-ocean-territory','name_en' => 'British Indian Ocean','name' => 'المحيط الهندي البريطاني','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BN','capital' => 'brunei','name_en' => 'Brunei Darussalam','name' => 'بروناي دار السلام','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BG','capital' => 'bulgaria','name_en' => 'Bulgaria','name' => 'بلغاريا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BF','capital' => 'burkina-faso','name_en' => 'Burkina Faso','name' => 'بوركينا فاسو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BI','capital' => 'burundi','name_en' => 'Burundi','name' => 'بوروندي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KH','capital' => 'cambodia','name_en' => 'Cambodia','name' => 'كمبوديا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CM','capital' => 'cameroon','name_en' => 'Cameroon','name' => 'الكاميرون','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CA','capital' => 'canada','name_en' => 'Canada','name' => 'كندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CV','capital' => 'cape-verde','name_en' => 'Cape Verde','name' => 'الرأس الأخضر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KY','capital' => 'cayman-islands','name_en' => 'Cayman Islands','name' => 'جزر كايمان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CF','capital' => 'central-african-republic','name_en' => 'Central African Republic','name' => 'جمهورية افريقيا الوسطى','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TD','capital' => 'chad','name_en' => 'Chad','name' => 'تشاد','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CL','capital' => 'chile','name_en' => 'Chile','name' => 'تشيلي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CN','capital' => 'china','name_en' => 'China','name' => 'الصين','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CX','capital' => 'christmas-island','name_en' => 'Christmas Island','name' => 'جزيرة الكريسماس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CC','capital' => 'cocos-island','name_en' => 'Cocos (Keeling) Islands','name' => 'جزر كوكوس (كيلينغ)','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CO','capital' => 'colombia','name_en' => 'Colombia','name' => 'كولومبيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KM','capital' => 'comoros','name_en' => 'Comoros','name' => 'جزر القمر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CK','capital' => 'cook-islands','name_en' => 'Cook Islands','name' => 'جزر كوك','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CR','capital' => 'costa-rica','name_en' => 'Costa Rica','name' => 'كوستا ريكا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CI','capital' => 'ivory-coast','name_en' => 'Côte d\'Ivoire','name' => 'كوت ديفوار','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'HR','capital' => 'croatia','name_en' => 'Croatia','name' => 'كرواتيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CU','capital' => 'cuba','name_en' => 'Cuba','name' => 'كوبا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CW','capital' => 'curacao','name_en' => 'Curaçao','name' => 'كوراساو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CZ','capital' => 'czech-republic','name_en' => 'Czech Republic','name' => 'الجمهورية التشيكية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'DK','capital' => 'denmark','name_en' => 'Denmark','name' => 'الدنمارك','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'DJ','capital' => 'djibouti','name_en' => 'Djibouti','name' => 'جيبوتي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'DM','capital' => 'dominica','name_en' => 'Dominica','name' => 'دومينيكا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'DO','capital' => 'dominican-republic','name_en' => 'Dominican Republic','name' => 'جمهورية الدومينيكان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'EC','capital' => 'ecuador','name_en' => 'Ecuador','name' => 'الاكوادور','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'EG','capital' => 'egypt','name_en' => 'Egypt','name' => 'مصر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SV','capital' => 'el-salvador','name_en' => 'El Salvador','name' => 'السلفادور','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GQ','capital' => 'equatorial-guinea','name_en' => 'Equatorial Guinea','name' => 'غينيا الإستوائية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ER','capital' => 'eritrea','name_en' => 'Eritrea','name' => 'إريتريا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'EE','capital' => 'estonia','name_en' => 'Estonia','name' => 'إستونيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ET','capital' => 'ethiopia','name_en' => 'Ethiopia','name' => 'أثيوبيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'FK','capital' => 'falkland-islands','name_en' => 'Falkland Islands (Malvinas)','name' => 'جزر فوكلاند (مالفيناس)','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'FJ','capital' => 'fiji','name_en' => 'Fiji','name' => 'فيجي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'FI','capital' => 'finland','name_en' => 'Finland','name' => 'فنلندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'FR','capital' => 'france','name_en' => 'France','name' => 'فرنسا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PF','capital' => 'french-polynesia','name_en' => 'French Polynesia','name' => 'بولينيزيا الفرنسية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GA','capital' => 'gabon','name_en' => 'Gabon','name' => 'الجابون','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GM','capital' => 'gambia','name_en' => 'Gambia','name' => 'غامبيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GE','capital' => 'georgia','name_en' => 'Georgia','name' => 'جورجيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'DE','capital' => 'germany','name_en' => 'Germany','name' => 'ألمانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GH','capital' => 'ghana','name_en' => 'Ghana','name' => 'غانا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GI','capital' => 'gibraltar','name_en' => 'Gibraltar','name' => 'جبل طارق','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GR','capital' => 'greece','name_en' => 'Greece','name' => 'اليونان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GL','capital' => 'greenland','name_en' => 'Greenland','name' => 'الأرض الخضراء','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GD','capital' => 'grenada','name_en' => 'Grenada','name' => 'غرينادا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GU','capital' => 'guam','name_en' => 'Guam','name' => 'غوام','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GT','capital' => 'guatemala','name_en' => 'Guatemala','name' => 'غواتيمالا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GG','capital' => 'guernsey','name_en' => 'Guernsey','name' => 'غيرنسي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GN','capital' => 'guinea','name_en' => 'Guinea','name' => 'غينيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GW','capital' => 'guinea-bissau','name_en' => 'Guinea-Bissau','name' => 'غينيا بيساو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'HT','capital' => 'haiti','name_en' => 'Haiti','name' => 'هايتي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'VA','capital' => 'vatican-city','name_en' => 'Holy See (Vatican City State)','name' => 'الكرسي الرسولي (دولة الفاتيكان)','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'HN','capital' => 'honduras','name_en' => 'Honduras','name' => 'هندوراس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'HK','capital' => 'hong-kong','name_en' => 'Hong Kong','name' => 'هونج كونج','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'HU','capital' => 'hungary','name_en' => 'Hungary','name' => 'هنغاريا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IS','capital' => 'iceland','name_en' => 'Iceland','name' => 'أيسلندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IN','capital' => 'india','name_en' => 'India','name' => 'الهند','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ID','capital' => 'indonesia','name_en' => 'Indonesia','name' => 'إندونيسيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IR','capital' => 'iran','name_en' => 'Iran, Islamic Republic of','name' => 'جمهورية إيران الإسلامية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IQ','capital' => 'iraq','name_en' => 'Iraq','name' => 'العراق','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IE','capital' => 'ireland','name_en' => 'Ireland','name' => 'أيرلندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IM','capital' => 'isle-of-man','name_en' => 'Isle of Man','name' => 'جزيرة آيل أوف مان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IL','capital' => 'israel','name_en' => 'Israel','name' => 'إسرائيل','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'IT','capital' => 'italy','name_en' => 'Italy','name' => 'إيطاليا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'JM','capital' => 'jamaica','name_en' => 'Jamaica','name' => 'جامايكا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'JP','capital' => 'japan','name_en' => 'Japan','name' => 'اليابان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'JE','capital' => 'jersey','name_en' => 'Jersey','name' => 'جيرسي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'JO','capital' => 'jordan','name_en' => 'Jordan','name' => 'الأردن','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KZ','capital' => 'kazakhstan','name_en' => 'Kazakhstan','name' => 'كازاخستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KE','capital' => 'kenya','name_en' => 'Kenya','name' => 'كينيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KI','capital' => 'kiribati','name_en' => 'Kiribati','name' => 'كيريباتي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KP','capital' => 'north-korea','name_en' => 'Korea, Democratic People\'s Republic of','name' => 'كوريا، الجمهورية الشعبية الديمقراطية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KW','capital' => 'kuwait','name_en' => 'Kuwait','name' => 'الكويت','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KG','capital' => 'kyrgyzstan','name_en' => 'Kyrgyzstan','name' => 'قيرغيزستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LA','capital' => 'laos','name_en' => 'Lao People\'s Democratic Republic','name' => 'جمهورية لاو الديمقراطية الشعبية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LV','capital' => 'latvia','name_en' => 'Latvia','name' => 'لاتفيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LB','capital' => 'lebanon','name_en' => 'Lebanon','name' => 'لبنان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LS','capital' => 'lesotho','name_en' => 'Lesotho','name' => 'ليسوتو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LR','capital' => 'liberia','name_en' => 'Liberia','name' => 'ليبيريا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LY','capital' => 'libya','name_en' => 'Libya','name' => 'ليبيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LI','capital' => 'liechtenstein','name_en' => 'Liechtenstein','name' => 'ليختنشتاين','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LT','capital' => 'lithuania','name_en' => 'Lithuania','name' => 'ليتوانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LU','capital' => 'luxembourg','name_en' => 'Luxembourg','name' => 'لوكسمبورغ','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MO','capital' => 'macao','name_en' => 'Macao','name' => 'ماكاو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MG','capital' => 'madagascar','name_en' => 'Madagascar','name' => 'مدغشقر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MW','capital' => 'malawi','name_en' => 'Malawi','name' => 'ملاوي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MY','capital' => 'malaysia','name_en' => 'Malaysia','name' => 'ماليزيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MV','capital' => 'maldives','name_en' => 'Maldives','name' => 'جزر المالديف','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ML','capital' => 'mali','name_en' => 'Mali','name' => 'مالي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MT','capital' => 'malta','name_en' => 'Malta','name' => 'مالطا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MH','capital' => 'marshall-island','name_en' => 'Marshall Islands','name' => 'جزر مارشال','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MQ','capital' => 'martinique','name_en' => 'Martinique','name' => 'مارتينيك','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MR','capital' => 'mauritania','name_en' => 'Mauritania','name' => 'موريتانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MU','capital' => 'mauritius','name_en' => 'Mauritius','name' => 'موريشيوس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MX','capital' => 'mexico','name_en' => 'Mexico','name' => 'المكسيك','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'FM','capital' => 'micronesia','name_en' => 'Micronesia, Federated States of','name' => 'ولايات ميكرونيزيا الموحدة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MD','capital' => 'moldova','name_en' => 'Moldova, Republic of','name' => 'جمهورية مولدوفا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MC','capital' => 'monaco','name_en' => 'Monaco','name' => 'موناكو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MN','capital' => 'mongolia','name_en' => 'Mongolia','name' => 'منغوليا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ME','capital' => 'montenegro','name_en' => 'Montenegro','name' => 'الجبل الأسود','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MS','capital' => 'montserrat','name_en' => 'Montserrat','name' => 'مونتسيرات','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MA','capital' => 'morocco','name_en' => 'Morocco','name' => 'المغرب','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MZ','capital' => 'mozambique','name_en' => 'Mozambique','name' => 'موزمبيق','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MM','capital' => 'myanmar','name_en' => 'Myanmar','name' => 'ميانمار','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NA','capital' => 'namibia','name_en' => 'Namibia','name' => 'ناميبيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NR','capital' => 'nauru','name_en' => 'Nauru','name' => 'ناورو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NP','capital' => 'nepal','name_en' => 'Nepal','name' => 'نيبال','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NL','capital' => 'netherlands','name_en' => 'Netherlands','name' => 'هولندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NZ','capital' => 'new-zealand','name_en' => 'New Zealand','name' => 'نيوزيلندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NI','capital' => 'nicaragua','name_en' => 'Nicaragua','name' => 'نيكاراغوا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NE','capital' => 'niger','name_en' => 'Niger','name' => 'النيجر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NG','capital' => 'nigeria','name_en' => 'Nigeria','name' => 'نيجيريا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NU','capital' => 'niue','name_en' => 'Niue','name' => 'نيوي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NF','capital' => 'norfolk-island','name_en' => 'Norfolk Island','name' => 'جزيرة نورفولك','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MP','capital' => 'northern-mariana-islands','name_en' => 'Northern Mariana Islands','name' => 'جزر مريانا الشمالية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'NO','capital' => 'norway','name_en' => 'Norway','name' => 'النرويج','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'OM','capital' => 'oman','name_en' => 'Oman','name' => 'سلطنة عمان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PK','capital' => 'pakistan','name_en' => 'Pakistan','name' => 'باكستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PW','capital' => 'palau','name_en' => 'Palau','name' => 'بالاو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PS','capital' => 'palestine','name_en' => 'Palestinian Territory, Occupied','name' => 'الأراضي الفلسطينية المحتلة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PA','capital' => 'panama','name_en' => 'Panama','name' => 'بنما','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PG','capital' => 'papua-new-guinea','name_en' => 'Papua New Guinea','name' => 'بابوا غينيا الجديدة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PY','capital' => 'paraguay','name_en' => 'Paraguay','name' => 'باراغواي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PE','capital' => 'peru','name_en' => 'Peru','name' => 'بيرو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PH','capital' => 'philippines','name_en' => 'Philippines','name' => 'فيلبيني','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PL','capital' => 'poland','name_en' => 'Poland','name' => 'بولندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PT','capital' => 'portugal','name_en' => 'Portugal','name' => 'البرتغال','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'PR','capital' => 'puerto-rico','name_en' => 'Puerto Rico','name' => 'بورتوريكو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'QA','capital' => 'qatar','name_en' => 'Qatar','name' => 'دولة قطر','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'RO','capital' => 'romania','name_en' => 'Romania','name' => 'رومانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'RU','capital' => 'russia','name_en' => 'Russian Federation','name' => 'الاتحاد الروسي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'RW','capital' => 'rwanda','name_en' => 'Rwanda','name' => 'رواندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'BL','capital' => 'st-barts','name_en' => 'Saint Barthélemy','name' => 'سانت بارتيليمي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KN','capital' => 'saint-kitts-and-nevis','name_en' => 'Saint Kitts and Nevis','name' => 'سانت كيتس ونيفيس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LC','capital' => 'st-lucia','name_en' => 'Saint Lucia','name' => 'القديسة لوسيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'MF','capital' => 'sint-maarten','name_en' => 'Saint Martin (French part)','name' => 'سانت مارتن (الجزء الفرنسي)','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'VC','capital' => 'st-vincent-and-the-grenadines','name_en' => 'Saint Vincent and the','name' => 'سانت فنسنت و','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'WS','capital' => 'samoa','name_en' => 'Samoa','name' => 'ساموا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SM','capital' => 'san-marino','name_en' => 'San Marino','name' => 'سان مارينو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ST','capital' => 'sao-tome-and-prince','name_en' => 'Sao Tome and Principe','name' => 'ساو تومي وبرينسيبي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SA','capital' => 'saudi-arabia','name_en' => 'Saudi Arabia','name' => 'المملكة العربية السعودية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SN','capital' => 'senegal','name_en' => 'Senegal','name' => 'السنغال','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'RS','capital' => 'serbia','name_en' => 'Serbia','name' => 'صربيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SC','capital' => 'seychelles','name_en' => 'Seychelles','name' => 'سيشيل','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SL','capital' => 'sierra-leone','name_en' => 'Sierra Leone','name' => 'سيرا ليون','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SG','capital' => 'singapore','name_en' => 'Singapore','name' => 'سنغافورة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SK','capital' => 'slovakia','name_en' => 'Slovakia','name' => 'سلوفاكيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SI','capital' => 'slovenia','name_en' => 'Slovenia','name' => 'سلوفينيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SB','capital' => 'solomon-islands','name_en' => 'Solomon Islands','name' => 'جزر سليمان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SO','capital' => 'somalia','name_en' => 'Somalia','name' => 'الصومال','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ZA','capital' => 'south-africa','name_en' => 'South Africa','name' => 'جنوب أفريقيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'KR','capital' => 'south-korea','name_en' => 'South Korea','name' => 'كوريا الجنوبية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SS','capital' => 'south-sudan','name_en' => 'South Sudan','name' => 'جنوب السودان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ES','capital' => 'spain','name_en' => 'Spain','name' => 'إسبانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'LK','capital' => 'sri-lanka','name_en' => 'Sri Lanka','name' => 'سيريلانكا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SD','capital' => 'sudan','name_en' => 'Sudan','name' => 'السودان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SR','capital' => 'suriname','name_en' => 'Suriname','name' => 'سورينام','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SZ','capital' => 'swaziland','name_en' => 'Swaziland','name' => 'سوازيلاند','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SE','capital' => 'sweden','name_en' => 'Sweden','name' => 'السويد','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'CH','capital' => 'switzerland','name_en' => 'Switzerland','name' => 'سويسرا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'SY','capital' => 'syria','name_en' => 'Syrian Arab Republic','name' => 'الجمهورية العربية السورية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TW','capital' => 'taiwan','name_en' => 'Taiwan, Province of China','name' => 'تايوان ، مقاطعة الصين','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TJ','capital' => 'tajikistan','name_en' => 'Tajikistan','name' => 'طاجيكستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TZ','capital' => 'tanzania','name_en' => 'Tanzania, United Republic of','name' => 'جمهورية تنزانيا المتحدة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TH','capital' => 'thailand','name_en' => 'Thailand','name' => 'تايلاند','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TG','capital' => 'togo','name_en' => 'Togo','name' => 'توجو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TK','capital' => 'tokelau','name_en' => 'Tokelau','name' => 'توكيلاو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TO','capital' => 'tonga','name_en' => 'Tonga','name' => 'تونغا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TT','capital' => 'trinidad-and-tobago','name_en' => 'Trinidad and Tobago','name' => 'ترينداد وتوباغو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TN','capital' => 'tunisia','name_en' => 'Tunisia','name' => 'تونس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TR','capital' => 'turkey','name_en' => 'Turkey','name' => 'ديك رومى','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TM','capital' => 'turkmenistan','name_en' => 'Turkmenistan','name' => 'تركمانستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TC','capital' => 'turks-and-caicos','name_en' => 'Turks and Caicos Islands','name' => 'جزر تركس وكايكوس','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'TV','capital' => 'tuvalu','name_en' => 'Tuvalu','name' => 'توفالو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'UG','capital' => 'uganda','name_en' => 'Uganda','name' => 'أوغندا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'UA','capital' => 'ukraine','name_en' => 'Ukraine','name' => 'أوكرانيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'AE','capital' => 'united-arab-emirates','name_en' => 'United Arab Emirates','name' => 'الإمارات العربية المتحدة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'GB','capital' => 'united-kingdom','name_en' => 'United Kingdom','name' => 'المملكة المتحدة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'US','capital' => 'united-states','name_en' => 'United States','name' => 'الولايات المتحدة','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'UY','capital' => 'uruguay','name_en' => 'Uruguay','name' => 'أوروغواي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'UZ','capital' => 'uzbekistan','name_en' => 'Uzbekistan','name' => 'أوزبكستان','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'VU','capital' => 'vanuatu','name_en' => 'Vanuatu','name' => 'فانواتو','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'VE','capital' => 'venezuela','name_en' => 'Venezuela, Bolivarian Republic of','name' => 'فنزويلا ، جمهورية البوليفارية','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'VN','capital' => 'vietnam','name_en' => 'Vietnam','name' => 'فيتنام','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'VI','capital' => 'virgin-islands','name_en' => 'Virgin Islands','name' => 'جزر فيرجن','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'YE','capital' => 'yemen','name_en' => 'Yemen','name' => 'اليمن','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ZM','capital' => 'zambia','name_en' => 'Zambia','name' => 'زامبيا','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array('code' => 'ZW','capital' => 'zimbabwe','name_en' => 'Zimbabwe','name' => 'زيمبابوي','created_at' => Carbon::now()->format('Y-m-d H:i:s')),
        );

        DB::table('countries')->insert($admins);
    }
}

